FLASK_ENV = "development"
FLASK_DEBUG = "1"
SECRET_KEY = "dev-secret-key"

POSTGRES_DB = "digisutra"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "postgres"
POSTGRES_HOST = "localhost"
POSTGRES_DB_PORT = "5432"
POSTGRES_DB_URI = (
    f"postgresql+psycopg2://{POSTGRES_USER}:{POSTGRES_PASSWORD}"
    f"@{POSTGRES_HOST}:{POSTGRES_DB_PORT}/{POSTGRES_DB}"
)

RAZORPAY_KEY_ID = ""
RAZORPAY_KEY_SECRET = ""
RAZORPAY_WEBHOOK_SECRET = ""
RAZORPAY_CURRENCY = "INR"

AWS_REGION = "ap-south-1"
AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""
AWS_S3_BUCKET_NAME = ""
AWS_CLOUDFRONT_DOMAIN = ""
AWS_S3_PRESIGN_EXPIRES_IN = 900
AWS_S3_UPLOAD_PREFIX = "products"

APP_BASE_URL = "http://localhost:3000"
API_BASE_URL = "http://localhost:5000"
LOG_LEVEL = "INFO"
AUTH_EDDSA_PRIVATE_KEY_PEM = ""
AUTH_EDDSA_PUBLIC_KEY_PEM = ""
ASSET_ACCESS_MAX_DOWNLOADS = 3
ASSET_ACCESS_EXPIRES_IN_DAYS = 30
ASSET_DELIVERY_TOKEN_TTL_SECONDS = 900
