import { APP, COPY, ROUTES } from "../constants/app.js";
import { escapeHtml, money, date, productCover, renderProductCard, statusLabel } from "./helpers.js";

function header(session) {
  const account = session ? `<a class="avatar-link" href="${ROUTES.settings}" data-link><span class="avatar">${escapeHtml((session.first_name || session.username || "U")[0].toUpperCase())}</span><span>${escapeHtml(session.first_name || session.username)}</span></a>` : `<a class="button button-secondary" href="${ROUTES.auth}" data-link>Sign in</a>`;
  return `<header class="site-header"><a class="wordmark" href="${ROUTES.home}" data-link><span class="seal">DS</span><span><strong>${APP.name}</strong><small>${APP.tagline}</small></span></a><nav class="site-nav"><a href="${ROUTES.catalog}" data-link>Browse</a>${session ? `<a href="${ROUTES.library}" data-link>Library</a>` : ""}${session && session.user_type === APP.roles.customer ? `<a href="${ROUTES.becomeSeller}" data-link>Become a seller</a>` : ""}${session && [APP.roles.seller, APP.roles.admin].includes(session.user_type) ? `<a href="${ROUTES.seller}" data-link>Sell</a>` : ""}${session && session.user_type === APP.roles.admin ? `<a href="${ROUTES.adminSellerApplications}" data-link>Seller requests</a>` : ""}</nav><div class="header-actions"><a class="cart-link" href="${ROUTES.catalog}" data-link>Explore</a>${account}</div></header>`;
}

export function home({ session, products }) {
  return `${header(session)}<main class="page"><section class="hero"><div><span class="eyebrow">A marketplace for independent thinking</span><h1>Useful things,<br><em>made by people.</em></h1><p>Discover thoughtful templates, guides, prompts, and digital tools that help you make the next thing better.</p><div class="hero-actions"><a class="button button-primary" href="${ROUTES.catalog}" data-link>Browse the marketplace <span>↗</span></a><a class="text-link" href="${session ? ROUTES.library : ROUTES.auth}" data-link>${session ? "Open your library" : "Join DigiSutra"} <span>→</span></a></div></div><div class="hero-note"><span class="hero-note-mark">✦</span><strong>Made for the curious</strong><p>Every product is a small act of clarity—practical, considered, and ready to use.</p></div></section><section class="section-block"><div class="section-heading"><div><span class="eyebrow">Fresh from the shelf</span><h2>Explore what’s useful</h2></div><a class="text-link" href="${ROUTES.catalog}" data-link>View all <span>→</span></a></div><div class="product-grid">${products.slice(0, 4).map(renderProductCard).join("") || `<p class="muted">${COPY.emptyProducts}</p>`}</div></section><section class="principles"><div><span class="eyebrow">The DigiSutra approach</span><h2>Less noise.<br>More signal.</h2></div><div class="principle-list"><article><span>01</span><h3>Small and useful</h3><p>Products are made to help with a real next step, not to fill a shelf.</p></article><article><span>02</span><h3>Independent voices</h3><p>Support creators who turn experience into something you can use.</p></article><article><span>03</span><h3>Keep it close</h3><p>Purchased work stays in your library, ready whenever you need it.</p></article></div></section></main>${footer()}`;
}

export function catalog({ session, products, query = "", category = "all" }) {
  const categories = ["all", ...new Set(products.map((p) => p.category).filter(Boolean))];
  return `${header(session)}<main class="page"><section class="catalog-intro"><span class="eyebrow">The marketplace</span><h1>Browse useful work.</h1><p>Digital products for clearer thinking, better making, and the work between.</p></section><form class="catalog-toolbar" data-catalog-form><label class="search-field"><span>⌕</span><input name="q" value="${escapeHtml(query)}" placeholder="Search products" /></label><select name="category">${categories.map((item) => `<option value="${escapeHtml(item)}" ${item === category ? "selected" : ""}>${escapeHtml(item === "all" ? "All categories" : item)}</option>`).join("")}</select><button class="button button-secondary" type="submit">Search</button></form><section class="catalog-results"><div class="results-meta"><span>${products.length} products</span><span>Sorted by newest</span></div><div class="product-grid">${products.map(renderProductCard).join("") || `<div class="full-width">${COPY.emptyProducts}</div>`}</div></section></main>${footer()}`;
}

export function detail({ session, product }) {
  if (!product) return `${header(session)}<main class="page">${notFound("Product not found", "This product may have been unpublished or moved.")}</main>${footer()}`;
  return `${header(session)}<main class="page detail-page"><a class="back-link" href="${ROUTES.catalog}" data-link>← Back to marketplace</a><section class="detail-grid"><div>${productCover(product)}</div><div class="detail-copy"><span class="eyebrow">${escapeHtml(product.category || "Digital product")}</span><h1>${escapeHtml(product.title)}</h1><p class="detail-byline">By ${escapeHtml(product.owner_username || "Independent creator")}</p><div class="detail-price">${escapeHtml(money(product.currency, product.price))}</div><p>${escapeHtml(product.description || "This creator has not added a description yet.")}</p><button class="button button-primary button-wide" data-buy-product="${escapeHtml(product.uuid)}">${session ? "Add to your library" : "Sign in to purchase"} <span>→</span></button><div class="trust-row"><span>✓ Instant access</span><span>✓ Secure checkout</span><span>✓ Creator-supported</span></div></div></section><section class="detail-lower"><div><span class="eyebrow">About this product</span><h2>Made to be used.</h2><p>Digital work should earn its place in your workflow. This product is delivered to your library after a successful purchase.</p></div><div class="detail-faq"><div><strong>What do I get?</strong><span>Digital access after payment</span></div><div><strong>Can I get a refund?</strong><span>Refund requests are handled through your order</span></div></div></section></main>${footer()}`;
}

export function auth({ mode = "login" }) { return `<main class="auth-page"><a class="wordmark auth-wordmark" href="${ROUTES.home}" data-link><span class="seal">DS</span><span><strong>${APP.name}</strong><small>${APP.tagline}</small></span></a><section class="auth-layout"><div class="auth-message"><span class="eyebrow">Welcome to DigiSutra</span><h1>${COPY.authTitle}</h1><p>${COPY.authBody}</p></div><div class="auth-card"><div class="auth-tabs"><button class="tab ${mode === "login" ? "active" : ""}" data-auth-mode="login">Log in</button><button class="tab ${mode === "signup" ? "active" : ""}" data-auth-mode="signup">Create account</button></div><form data-auth-form data-mode="${mode}">${mode === "signup" ? `<div class="form-row"><label>First name<input name="first_name" required /></label><label>Last name<input name="last_name" /></label></div>` : ""}<label>Username<input name="username" autocomplete="username" required /></label>${mode === "signup" ? `<label>Email<input name="email" type="email" required /></label>` : ""}<label>Password<input name="password" type="password" autocomplete="current-password" required /></label><p class="form-error" data-form-error></p><button class="button button-primary button-wide" type="submit">${mode === "login" ? "Log in" : "Create customer account"} <span>→</span></button></form><p class="form-note">Public accounts start as customers. Seller access is reviewed separately.</p></div></section></main>`; }

export function library({ session, purchases }) { return `${header(session)}<main class="page workspace-page"><div class="workspace-heading"><div><span class="eyebrow">Your workspace</span><h1>Library</h1><p>Your purchased work, kept close.</p></div></div><section class="library-list">${purchases.length ? purchases.map((item) => `<article class="library-row"><div class="library-cover">DS</div><div class="library-info"><span class="eyebrow">${escapeHtml(item.product_title || "Digital product")}</span><h3>${escapeHtml(item.product_title || "Untitled product")}</h3><p>Purchased ${escapeHtml(date(item.created_on))}</p></div><span class="status status-${escapeHtml(item.delivery_status || "pending")}">${escapeHtml(statusLabel(item.delivery_status))}</span><button class="button button-secondary" data-library-order="${escapeHtml(item.uuid)}">Open</button></article>`).join("") : `<div class="panel-card"><h3>Your library is waiting.</h3><p>Purchase a product and it will appear here with its access and order status.</p><a class="button button-primary" href="${ROUTES.catalog}" data-link>Browse products</a></div>`}</section></main>${footer()}`; }

export function seller({ session, summary, products }) { const s = summary || {}; return `${header(session)}<main class="page workspace-page"><div class="workspace-heading"><div><span class="eyebrow">Creator workspace</span><h1>Seller overview</h1><p>Keep your catalogue and operations in view.</p></div><a class="button button-primary" href="${ROUTES.sellerProducts}" data-link>Manage products <span>→</span></a></div><section class="metric-grid">${[["Gross sales", money(APP.defaultCurrency, s.gross_sales_amount)], ["Net seller amount", money(APP.defaultCurrency, s.net_seller_amount)], ["Products", s.products_count ?? 0], ["Available for payout", money(APP.defaultCurrency, s.available_for_payout)]].map(([label, value]) => `<article class="metric-card"><span>${label}</span><strong>${escapeHtml(value)}</strong></article>`).join("")}</section><section class="workspace-grid"><div class="panel-card"><div class="section-heading"><div><span class="eyebrow">Catalogue</span><h2>Your products</h2></div><a class="text-link" href="${ROUTES.sellerProducts}" data-link>View all →</a></div>${products.slice(0, 4).map((p) => `<div class="mini-row"><div>${productCover(p, true)}</div><div><strong>${escapeHtml(p.title)}</strong><span>${escapeHtml(p.category || "Digital product")}</span></div><span>${escapeHtml(money(p.currency, p.price))}</span></div>`).join("") || `<p class="muted">No products yet.</p>`}</div><div class="panel-card accent-card"><span class="eyebrow">Payout readiness</span><h2>${s.payout_hold ? "Payouts are on hold" : s.payout_ready ? "Ready for payout" : "Complete your profile"}</h2><p>${s.payout_hold ? "An admin has placed a temporary hold on payouts." : s.payout_ready ? "Your available balance is ready to request." : "Finish your seller profile before requesting payouts."}</p><a class="text-link" href="${ROUTES.sellerPayouts}" data-link>Review payouts →</a></div></section></main>${footer()}`; }

export function sellerProducts({ session, products }) { return `${header(session)}<main class="page workspace-page"><div class="workspace-heading"><div><span class="eyebrow">Creator workspace</span><h1>Products</h1><p>Manage the digital work you have published.</p></div><a class="button button-primary" href="${ROUTES.sellerProductNew}" data-link>Add product <span>→</span></a></div><div class="table-card"><div class="table-head"><span>Product</span><span>Category</span><span>Price</span><span>Status</span></div>${products.map((p) => `<div class="table-row"><div><strong>${escapeHtml(p.title)}</strong><small>${escapeHtml(p.description || "No description")}</small></div><span>${escapeHtml(p.category || "—")}</span><span>${escapeHtml(money(p.currency, p.price))}</span><span class="status status-${p.is_active && p.is_public ? "ready" : "draft"}">${p.is_active && p.is_public ? "Published" : "Draft"}</span></div>`).join("") || `<p class="empty-table">No products yet.</p>`}</div></main>${footer()}`; }

export function sellerProductNew({ session }) { return `${header(session)}<main class="page workspace-page"><div class="workspace-heading"><div><span class="eyebrow">Creator workspace</span><h1>Add product</h1><p>Create a catalogue entry. Ownership and publish permissions remain server-enforced.</p></div></div><div class="panel-card form-panel"><form data-product-form><label>Title<input name="title" required /></label><label>Description<textarea name="description" rows="5"></textarea></label><div class="form-row"><label>Price<input name="price" inputmode="decimal" required /></label><label>Currency<input name="currency" value="${APP.defaultCurrency}" /></label></div><label>Category<input name="category" placeholder="Templates, prompts, guides…" /></label><p class="form-error" data-form-error></p><button class="button button-primary" type="submit">Create product <span>→</span></button></form></div></main>${footer()}`; }

export function sellerPayouts({ session, summary }) { const s = summary || {}; return `${header(session)}<main class="page workspace-page"><div class="workspace-heading"><div><span class="eyebrow">Creator workspace</span><h1>Payouts</h1><p>Balances and payout history returned by DigiSutra.</p></div></div><section class="metric-grid"><article class="metric-card"><span>Available</span><strong>${escapeHtml(money(s.currency, s.available_for_payout))}</strong></article><article class="metric-card"><span>Pending</span><strong>${escapeHtml(money(s.currency, s.pending_payout))}</strong></article><article class="metric-card"><span>Readiness</span><strong>${s.payout_ready ? "Ready" : "Not ready"}</strong></article></section><div class="table-card"><div class="table-head"><span>Created</span><span>Method</span><span>Amount</span><span>Status</span></div>${(s.payouts || []).map((p) => `<div class="table-row"><span>${escapeHtml(date(p.created_on))}</span><span>${escapeHtml(p.payout_method || "Manual")}</span><span>${escapeHtml(money(s.currency, p.amount))}</span><span class="status status-${escapeHtml(p.status)}">${escapeHtml(statusLabel(p.status))}</span></div>`).join("") || `<p class="empty-table">No payouts recorded yet.</p>`}</div></main>${footer()}`; }

export function settings({ session }) {
  const adminCard = session.user_type === APP.roles.admin ? `<div class="panel-card"><h3>Seller requests</h3><p>Review pending seller applications and approve, reject, or request more information.</p><a class="button button-primary" href="${ROUTES.adminSellerApplications}" data-link>Review requests <span>→</span></a></div>` : "";
  return `${header(session)}<main class="page workspace-page"><div class="workspace-heading"><div><span class="eyebrow">Account</span><h1>${escapeHtml(session.first_name || session.username || "Account")}</h1><p>${escapeHtml(session.email || session.username || "")}</p></div><button class="button button-secondary" type="button" data-logout>Log out</button></div><section class="workspace-grid"><div class="panel-card"><h3>Library</h3><p>Open your purchased products, delivery status, and invoices.</p><a class="button button-primary" href="${ROUTES.library}" data-link>Open library <span>→</span></a></div><div class="panel-card accent-card"><h3>${session.user_type === APP.roles.customer ? "Seller access" : "Creator workspace"}</h3><p>${session.user_type === APP.roles.customer ? "Apply to publish products and manage payouts." : "Manage your catalogue, sales, and payout readiness."}</p><a class="button button-secondary" href="${session.user_type === APP.roles.customer ? ROUTES.becomeSeller : ROUTES.seller}" data-link>${session.user_type === APP.roles.customer ? "Become a seller" : "Open seller workspace"} <span>→</span></a></div>${adminCard}</section></main>${footer()}`;
}

export function sellerApplication({ session, application }) {
  const app = application || {};
  const locked = ["submitted", "under_review", "approved"].includes(app.status);
  return `${header(session)}<main class="page workspace-page"><div class="workspace-heading"><div><span class="eyebrow">Seller onboarding</span><h1>Become a seller</h1><p>Submit your creator profile for review.</p></div><span class="status status-${escapeHtml(app.status || "draft")}">${escapeHtml(statusLabel(app.status || "not started"))}</span></div><div class="panel-card form-panel"><form data-seller-application-form><div class="form-row"><label>Store name<input name="store_name" value="${escapeHtml(app.store_name || "")}" required ${locked ? "disabled" : ""} /></label><label>Category<input name="category" value="${escapeHtml(app.category || "")}" required ${locked ? "disabled" : ""} /></label></div><label>Store description<textarea name="store_description" rows="4" required ${locked ? "disabled" : ""}>${escapeHtml(app.store_description || "")}</textarea></label><label>Product types<input name="product_types" value="${escapeHtml(app.product_types || "")}" placeholder="Templates, guides, prompts" required ${locked ? "disabled" : ""} /></label><div class="form-row"><label>Legal name<input name="legal_name" value="${escapeHtml(app.legal_name || "")}" required ${locked ? "disabled" : ""} /></label><label>Country<input name="country" value="${escapeHtml(app.country || "")}" required ${locked ? "disabled" : ""} /></label></div><div class="form-row"><label>Phone number<input name="phone_number" value="${escapeHtml(app.phone_number || "")}" required ${locked ? "disabled" : ""} /></label><label>Website<input name="website_url" value="${escapeHtml(app.website_url || "")}" ${locked ? "disabled" : ""} /></label></div><label>Portfolio URL<input name="portfolio_url" value="${escapeHtml(app.portfolio_url || "")}" ${locked ? "disabled" : ""} /></label><label class="check-row"><input type="checkbox" name="terms_accepted" ${app.terms_accepted ? "checked" : ""} ${locked ? "disabled" : ""} /> I accept the seller terms</label><p class="form-error" data-form-error>${escapeHtml(app.review_note || "")}</p>${locked ? "" : `<div class="form-actions"><button class="button button-secondary" type="submit" data-seller-application-action="draft">Save draft</button><button class="button button-primary" type="submit" data-seller-application-action="submit">Submit for review <span>→</span></button></div>`}</form></div></main>${footer()}`;
}

export function adminSellerApplications({ session, applications }) {
  const rows = applications.map((item) => {
    const canReview = ["submitted", "under_review", "needs_information"].includes(item.status);
    return `<article class="admin-request-row"><div><span class="eyebrow">${escapeHtml(item.category || "Seller request")}</span><h3>${escapeHtml(item.store_name || "Unnamed store")}</h3><p>${escapeHtml(item.store_description || "No description provided.")}</p><small>${escapeHtml(item.applicant?.email || item.applicant?.username || "Unknown applicant")} · ${escapeHtml(date(item.submitted_on || item.created_on))}</small></div><span class="status status-${escapeHtml(item.status)}">${escapeHtml(statusLabel(item.status))}</span><div class="form-actions">${canReview ? `<button class="button button-primary" type="button" data-admin-seller-action="approve" data-application-uuid="${escapeHtml(item.uuid)}">Approve</button><button class="button button-secondary" type="button" data-admin-seller-action="request-information" data-application-uuid="${escapeHtml(item.uuid)}">Request info</button><button class="button button-secondary" type="button" data-admin-seller-action="reject" data-application-uuid="${escapeHtml(item.uuid)}">Reject</button>` : ""}</div></article>`;
  }).join("");
  return `${header(session)}<main class="page workspace-page"><div class="workspace-heading"><div><span class="eyebrow">Admin</span><h1>Seller requests</h1><p>Approve seller access or send applications back for more detail.</p></div><button class="button button-secondary" type="button" data-refresh-admin-sellers>Refresh</button></div><section class="admin-request-list">${rows || `<div class="panel-card"><h3>No seller requests</h3><p>Submitted seller applications will appear here.</p></div>`}</section></main>${footer()}`;
}

export function checkout({ session, product, checkout }) {
  if (!product) return `${header(session)}<main class="page">${notFound("Product not found", "This product may have been unpublished or moved.")}</main>${footer()}`;
  const order = checkout?.order;
  const provider = checkout?.provider;
  return `${header(session)}<main class="page checkout-page"><a class="back-link" href="/products/${encodeURIComponent(product.uuid)}" data-link>← Back to product</a><section class="checkout-grid"><div class="panel-card"><span class="eyebrow">Checkout</span><h1>${escapeHtml(product.title)}</h1><p>${escapeHtml(product.description || "Digital access after payment confirmation.")}</p><div class="checkout-total"><span>Total</span><strong>${escapeHtml(money(product.currency, product.price))}</strong></div></div><div class="panel-card payment-panel"><span class="eyebrow">Payment</span>${order ? `<h2>Payment order ready</h2><p>Order ${escapeHtml(order.provider_order_id || order.uuid)} is ready for Razorpay checkout.</p><button class="button button-primary button-wide" data-open-razorpay>Pay with Razorpay <span>→</span></button><p class="form-note">Use Razorpay test card details in the popup. Access is added to your library after confirmation.</p>` : `<h2>Review and continue</h2><p>We will create your order and send you to Razorpay test checkout.</p><button class="button button-primary button-wide" data-start-checkout="${escapeHtml(product.uuid)}">Continue to payment <span>→</span></button>`}<p class="form-error" data-checkout-error></p>${provider ? `<pre class="debug-box">${escapeHtml(JSON.stringify(provider, null, 2))}</pre>` : ""}</div></section></main>${footer()}`;
}

function footer() { return `<footer class="site-footer"><span>© ${new Date().getFullYear()} ${APP.name}</span><span>Thoughtful digital work, kept simple.</span></footer>`; }
function notFound(title, body) { return `<div class="not-found"><h1>${escapeHtml(title)}</h1><p>${escapeHtml(body)}</p><a class="button button-primary" href="${ROUTES.catalog}" data-link>Return to marketplace</a></div>`; }
